# -*- coding: utf-8 -*-
{
    'name': 'Studio customizations',
    'version': '14.0.1.0',
    'category': 'Studio',
    'description': u"""
This module has been generated by Odoo Studio.
It contains the apps created with Studio and the customizations of existing apps.
""",
    'author': 'Meximp Technologies',
    'depends': [
        'account',
        'base',
        'product',
        'product_expiry',
        'project',
        'purchase',
        'purchase_stock',
        'repair',
        'sale',
        'sale_stock',
        'stock',
        'web',
        
    ],
    'data': [
        'data/report_paperformat.xml',
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/ir_actions_report.xml',
        'data/ir_default.xml',
    ],
    'application': False,
    'license': 'OPL-1',
}
